### ISSUE TITLE
Out of the box Reachy incompatibility 

### ISSUE THREAD

**Issue by VBorjaDD** [pollen-robotics/otis#2]
The out of the box version does not include Python 3, pip command launches version 2.7 which crash due to the parameter "encoding"

**Comment by pierre-rouanet** [comment]
Hi @VBorjaDD,

Python3 should come with the raspberry-pi install and be accessible via /usr/bin/python3 and pip3 via /usr/bin/pip3. Both Python3 and Python2 are installed and the default is still Python2.

You can check the complete install process that we use here: https://pollen-robotics.github.io/reachy-docs/docs/appendices/install-from-scratch-raspberry/

**Comment by VBorjaDD** [comment]
Great! Maybe it was just an update for Python 3 and the matter that the default one is Python2, if you are aware of it we can close it :) just wanted to inform you that it wasn't straightforward, especially for students or people just starting in python.

**Comment by pierre-rouanet** [comment]
Thanks for the feedback, we'll try to make it clearer in the doc!
